name: Blockparty Exam CICD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out source
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"

      # Set ECR Repo URL from GitHub secret
      - name: Set ECR Repo URL
        id: repo
        run: echo "::set-output name=ecr_url::${{ secrets.ECR_REPOSITORY_URL }}"

      # Log in to Amazon ECR
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region "us-east-1" \
          | docker login --username AWS --password-stdin "${{ steps.repo.outputs.ecr_url }}"

      # Build and push image to ECR
      - name: Build and Push to ECR
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.repo.outputs.ecr_url }}:latest
